<?php

namespace VMB\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use VMB\UserBundle\Entity\User;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{   
    public function getComments($page, $nbPerPage, discussion $discussion)
	{   
		$builder = $this->createQueryBuilder('c')
            ->where('c.discussion = :discussion')
              ->setParameter('discussion', $discussion)
            ->orderBy('c.date','ASC')
		;


		$query = $builder->getQuery();
		$query->setFirstResult(($page-1) * $nbPerPage)
			  ->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}
    
    public function getMyComments($page, $nbPerPage, User $user)
	{   
		$builder = $this->createQueryBuilder('c')
            ->where('c.user = :user')
              ->setParameter('user', $user)
            ->orderBy('c.date','ASC')
		;


		$query = $builder->getQuery();
		$query->setFirstResult(($page-1) * $nbPerPage)
			  ->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}
    
    public function searchWithQuery($query)
	{
		$builder = $this->createQueryBuilder('c')
					  ->orderBy('c.date', 'DESC');

		if($query !== null) {
			$builder->andWhere('c.description LIKE :q')->setParameter('q', '%'.$query.'%');
		}


		return $builder->getQuery()->getResult();
	}
}
