resource:
    path:     /
    defaults: { _controller: "VMBResourceBundle:Resource:index" }
    
resource_show:
    path:     /show/{id}
    defaults: { _controller: "VMBResourceBundle:Resource:show" }
    requirements:
        id: \d{1,}

resource_new:
    path:     /new/{is_modal}
    defaults: { _controller: "VMBResourceBundle:Upload:new", is_modal:false }

resource_edit:
    path:     /edit/{id}
    defaults: { _controller: "VMBResourceBundle:Upload:edit" }
    requirements:
        id:   \d{1,}

resource_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBResourceBundle:Resource:delete" }
    requirements:
        id:   \d{1,}

resource_search:
    path:     /search
    defaults: { _controller: "VMBResourceBundle:Resource:search" }
    requirements:
        _method: POST
