<?php

namespace VMB\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
	public function findByTopicSortedByType($topic, $official =  true, $user = null, $exclusive = false)
	{
		$qb = $this
			->createQueryBuilder('r')
			->orderBy('r.type')
			->where('r.topic = :topic')
			->setParameter('topic', $topic)
		;
		
		if($official !== null) {
			$qb->andWhere('r.trusted = :official')->setParameter('official', $official);
		}
		
		if($user != null) {
			if($exclusive) {
				$qb->andWhere('r.owner <> :user')->setParameter('user', $user);
			}
			else {
				$qb->andWhere('r.owner = :user')->setParameter('user', $user);
			}
		}
		return $qb
		->getQuery()
		->getResult();
	}
	
	public function findByKeyword($keyword, $topicId = null)
	{
		$qb = $this
			->createQueryBuilder('r')
			->orderBy('r.type')
		;
		$qb->where('r.title LIKE :keyword')->setParameter('keyword', '%'.$keyword.'%');
		
		if($topicId !== null) {
			$qb->andWhere('IDENTITY(r.topic) = :topicId')->setParameter('topicId', $topicId);
		}

		return $qb
		->getQuery()
		->getResult();
	}
}
