vmb_search:
    resource: "@VMBSearchBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    path:     /
    defaults: 
        _controller: FrameworkBundle:Template:template
        template: views/default/index.html.twig

vmb_contextual_help:
    resource: "@VMBContextualHelpBundle/Resources/config/routing.yml"
    prefix:   /

vmb_resource:
    resource: "@VMBResourceBundle/Resources/config/routing.yml"
    prefix:   /

vmb_presentation:
    resource: "@VMBPresentationBundle/Resources/config/routing.yml"
    prefix:   /

vmb_user:
    resource: "@VMBUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans
