# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.locale_listener:
        class: VMB\PresentationBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    #Implementing Entity listener classes
    topic.presentation_counts_listener:
        class: VMB\PresentationBundle\Entity\TopicListener
        tags:
            - { name: doctrine.orm.entity_listener }
    prensetation.add_topic_count_listener:
        class: VMB\PresentationBundle\Entity\PresentationListener
        tags:
            - { name: doctrine.orm.entity_listener }
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
            
    fos_user.doctrine_registry:
        alias: doctrine
            
    vmb.evaluation.listener:
        class: VMB\QuizBundle\Evaluation\EvalListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: destroyEvalConstants }