<?php

namespace VMB\PresentationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrixRepository extends EntityRepository
{
	public function getMatrixWithResources($id)
	{
		$qb = $this
			->createQueryBuilder('m')
			->leftJoin('m.povs', 'pov')
			->addSelect('pov')
			->leftJoin('m.levels', 'lvl')
			->addSelect('lvl')
			->leftJoin('m.resources', 'usedR')
			->addSelect('usedR')
			->leftJoin('usedR.resource', 'r')
			->addSelect('r')
			->orderBy('lvl.sort', 'ASC')
			->addOrderBy('pov.sort', 'ASC')
			->where('m.id = :id')
			->setParameter('id', $id)
		;

		return $qb
		->getQuery()
		->getSingleResult();
	}
}
