<?php

namespace VMB\PresentationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OntologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntologyRepository extends EntityRepository
{
}
