<?php

namespace VMB\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NumericalValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumericalValueRepository extends EntityRepository
{
}