<?php

namespace VMB\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionRepository extends EntityRepository
{
}
