<?php

namespace VMB\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findHintsByIds($idQuests)
    {
        $query = $this->_em->createQueryBuilder()
        ->select('q.hint')
        ->from($this->_entityName, 'q');
        $query->where($query->expr()->in('q.id', $idQuests));
        return $query->getQuery()->getResult();
    }
    
    public function findQuestionsByIds($idQuests)
    {
        $query = $this->_em->createQueryBuilder()
        ->select('q')
        ->from($this->_entityName, 'q');
        $query->where($query->expr()->in('q.id', $idQuests));
        return $query->getQuery()->getResult();
    }
}
