vmb_search_action:
    path:     /search # /{query}/{type}/{page}
    defaults: { _controller: "VMBSearchBundle:Search:index" }
    requirements:
        #type: "presentation|resource"
        #page: \d*
