vmb_search_action:
    path:     /search/{query}/{type}/{page}
    defaults: { _controller: "VMBSearchBundle:Search:index", type: "presentation", page: 1, query:""}
    requirements:
        #type: "presentation|resource"
        #page: \d*
