vmb_resource_homepage:
    path:     /resource/
    defaults: { _controller: VMBResourceBundle:Default:index }

vmb_resource_upload:
    path:     /resource/upload
    defaults: { _controller: VMBResourceBundle:Upload:form }
