services:
#    vmb_resource.example:
#        class: VMB\ResourceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
dubture_f_fmpeg:
    ffmpeg_binary: /usr/bin/ffmpeg
    ffprobe_binary: /usr/bin/ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4