<?php

namespace VMB\ContextualHelpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HelpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRepository extends EntityRepository
{
	public function getHelp($route)
	{
		$builder = $this->createQueryBuilder('h');
		$builder->andWhere('h.route LIKE :route')->setParameter('route', '%'.$route.'%');

		$result = $builder->getQuery()->getResult();
		foreach($result as $help) {
			if(in_array($route, $help->getRoute())) {
				return $help;
			}
		}
		return null;
	}
}
