admin_user:
    path:     /
    defaults: { _controller: "VMBUserBundle:User:index" }

admin_user_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBUserBundle:User:delete" }
    requirements:
        id:   \d{1,}
