vmb_presentation_topic:
    resource: "@VMBPresentationBundle/Resources/config/routing/topic.yml"
    prefix:   /topic

vmb_presentation_presentation:
    resource: "@VMBPresentationBundle/Resources/config/routing/presentation.yml"
    prefix:   /presentation

vmb_presentation_matrix:
    resource: "@VMBPresentationBundle/Resources/config/routing/matrix.yml"
    prefix:   /matrix

vmb_presentation_ontology:
    resource: "@VMBPresentationBundle/Resources/config/routing/ontology.yml"
    prefix:   /ontology

vmb_presentation_browse:
    path:     /browse/{page}
    defaults: { _controller: "VMBPresentationBundle:Presentation:browse", page: 1 }
    requirements:
        page: \d*

vmb_presentation_browse_topic:
    path:     /browse/topic/{topic}/{page}
    defaults: { _controller: "VMBPresentationBundle:Presentation:browse", page: 1 }
    requirements:
        topic: \d{1,}
        page: \d*

