parameters:
    ontology.class: VMB\PresentationBundle\Model\ontologyModel

services:
    security.authentication.customized_success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments:  [@router, @security.context]
    ontology:
        class: %ontology.class%
        arguments: [@database_connection, @kernel]
