annotation_edit:
    path:     /edit/{id}/{a}
    defaults: { _controller: "VMBPresentationBundle:Annotation:edit", a: null }
    requirements:
        id:   \d{1,}
        a:   \d{1,}

annotation_add:
    path:     /add
    defaults: { _controller: "VMBPresentationBundle:Annotation:add" }
    requirements:
        _method: POST
    
annotation_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBPresentationBundle:Annotation:delete" }
    requirements:
        id:   \d{1,}
