matrix:
    path:     /
    defaults: { _controller: "VMBPresentationBundle:Matrix:index" }

matrix_show:
    path:     /show/{id}
    defaults: { _controller: "VMBPresentationBundle:Matrix:show"}
    requirements:
        id:   \d{1,}

matrix_new:
    path:     /new
    defaults: { _controller: "VMBPresentationBundle:Matrix:new" }

matrix_edit:
    path:     /edit/{id}/{is_modal}
    defaults: { _controller: "VMBPresentationBundle:Matrix:edit" , is_modal:false }
    requirements:
        id:   \d{1,}

matrix_update:
    path:	  /update/{id}
    defaults: { _controller: "VMBPresentationBundle:Matrix:update" }
    requirements:
        _method: POST
        id:   \d{1,}

matrix_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBPresentationBundle:Matrix:delete" }
    requirements:
        id:   \d{1,}
        
matrix_official:
    path:     /official/{id}
    defaults: { _controller: "VMBPresentationBundle:Matrix:official" }
    requirements:
        id:   \d{1,}

matrix_delete_row:
    path:     /deleteRow/
    defaults: { _controller: "VMBPresentationBundle:Matrix:deleteRow" }
    requirements:
        _method: POST
        

matrix_edit_row:
    path:     /editRow/
    defaults: { _controller: "VMBPresentationBundle:Matrix:editRow" }
    requirements:
        _method: POST
