presentation:
    path:      /{page}
    defaults:  { _controller: "VMBPresentationBundle:Presentation:index", page: 1 }
    requirements:
        page: \d*
    
presentation_perso:
    path:     /
    defaults: { _controller: "VMBPresentationBundle:Presentation:personalIndex" }

presentation_show:
    path:     /show/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:show" }
    requirements:
        id:   \d{1,}

presentation_new:
    path:     /new/{idMatrix}
    defaults: { _controller: "VMBPresentationBundle:Presentation:new" }
    requirements:
        idMatrix:   \d{1,}

presentation_edit:
    path:     /edit/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:edit" }
    requirements:
        id:   \d{1,}
      

presentation_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:delete" }
    requirements:
        id:   \d{1,}
