presentation:
    path:     /
    defaults: { _controller: "VMBPresentationBundle:Presentation:index" }

presentation_show:
    path:     /show/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:show" }
    requirements:
        id:   \d{1,}

presentation_new:
    path:     /new
    defaults: { _controller: "VMBPresentationBundle:Presentation:new" }

presentation_edit:
    path:     /edit/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:edit" }
    requirements:
        id:   \d{1,}
      

presentation_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:delete" }
    requirements:
        id:   \d{1,}
