presentation:
    path:      /{page}
    defaults:  { _controller: "VMBPresentationBundle:Presentation:index", page: 1 }
    requirements:
        page: \d*
    
presentation_perso:
    path:     /personal/{page}
    defaults: { _controller: "VMBPresentationBundle:Presentation:personalIndex", page: 1 }
    requirements:
        page: \d*

presentation_show:
    path:     /show/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:show" }
    requirements:
        id:   \d{1,}
        
presentation_complementary:
    path:     /show/additional/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:additionalContent" }
    requirements:
        id:   \d{1,}        

presentation_new:
    path:     /new/{idMatrix}
    defaults: { _controller: "VMBPresentationBundle:Presentation:new" }
    requirements:
        idMatrix:   \d{1,}

presentation_edit:
    path:     /edit/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:edit" }
    requirements:
        id:   \d{1,}
        
presentation_create_copy:
    path:     /createFrom/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:createFrom" }
    requirements:
        id:   \d{1,}

presentation_delete:
    path:     /delete/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:delete" }
    requirements:
        id:   \d{1,}
        
presentation_deep_copy:
    path:     /copy/{id}
    defaults: { _controller: "VMBPresentationBundle:Presentation:deepCopy" }
    requirements:
        id:   \d{1,}
        
presentation_parameter:
    path:     /parameter/{param}/{id}/{value}
    defaults: { _controller: "VMBPresentationBundle:Presentation:parameter" }
    requirements:
        id:   \d{1,}        
        param: default|official|public
        value: 0|1
